apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akumar-coe/gitops-abot.git
    targetRevision: main
    path: apps/abot-app
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
